### ISSUE TITLE
istudybucket logo returns 404 page

### ISSUE THREAD

**Issue by Burnleydev1** [istudybucket/istudybucket-backend#34]

**Comment by elroykanye** [comment]
I am quite confused on this. Do you mean what is on the README?

**Comment by Burnleydev1** [comment]
Yes that on the Readme.md file.

**Comment by elroykanye** [comment]
Ah okay. We do not have a logo in the first place. Putting a template image there may work out anyway. 
This is legit

**Comment by Burnleydev1** [comment]
Okay sounds good.

**Comment by Burnleydev1** [comment]
Which image do you suggest is placed there?

**Comment by elroykanye** [comment]
there is no more need for a logo. Modern problems require modern solutions :)
So I will be closing this. Thank you very much.
