### ISSUE TITLE
Add an issue template to .github

### ISSUE THREAD

**Issue by Burnleydev1** [istudybucket/istudybucket-backend#35]
This is to help the person creating the issue to be much more elaborate on the issue (maybe a feature request or a bug report).

**Comment by Burnleydev1** [comment]
If this is accepted, I will like on it.

**Comment by elroykanye** [comment]
Hello @Burnleydev1 , I am only getting to see this now. Please carry on with this. I am actively resuming work on this project

**Comment by elroykanye** [comment]
Maybe you could make a suggestion for a PR template too, as an issue :)

**Comment by Burnleydev1** [comment]
Okay I will do that too

**Comment by Burnleydev1** [comment]
There issue template option under settings/features is not visible to me, please @elroykanye can you give it a look?

**Comment by elroykanye** [comment]
I will

**Comment by elroyvince** [comment]
Check it out on Insights/Community Standards

**Comment by Burnleydev1** [comment]
@elroyvince
Can you see what is in the snipet below on your end?
Because I am not seeing in on mine 
![Screenshot from 2022-04-18 14-58-43](https://user-images.githubusercontent.com/81782853/163819045-c3a10342-2539-4666-b687-2d33f4a8d36f.png)

**Comment by Burnleydev1** [comment]
That on community standards is how this project compares to [recommended community standards](https://opensource.guide/).

**Comment by elroykanye** [comment]
Ah okay. Yes I can see this image you sent. Is it possible to generate this on your fork and open a pr with it.

**Comment by Burnleydev1** [comment]
I'm not seeing this on my fork

**Comment by elroykanye** [comment]
I should add you to the org then

**Comment by Burnleydev1** [comment]
This is what I'm getting.
![Screenshot from 2022-04-18 16-28-10](https://user-images.githubusercontent.com/81782853/163831799-d0fc1247-6f1a-4f5f-95a9-6548657d71e4.png)

**Comment by elroykanye** [comment]
Check if you see different now

**Comment by Burnleydev1** [comment]
Yes but I saw this time on the community standards.

**Comment by Burnleydev1** [comment]
I ahve sent a [PR](https://github.com/istudybucket/istudybucket-backend/pull/40) for this issue

**Comment by elroykanye** [comment]
Alright, thanks

**Comment by Burnleydev1** [comment]
Closed by https://github.com/istudybucket/istudybucket-backend/pull/40
