### ISSUE TITLE
Add a contributing.md file

### ISSUE THREAD

**Issue by Burnleydev1** [istudybucket/istudybucket-backend#41]
Add a contributing.md file to guide those looking to contribute to this project but are new to open source or don't know how to proceed.

**Comment by elroykanye** [comment]
What will this project literally do without you? 😅 Thanks for this

**Comment by Burnleydev1** [comment]
A lot :)

**Comment by Burnleydev1** [comment]
I still don't really know a way of implementing a good contributing.md file.
