### ISSUE TITLE
post created date showing null

### ISSUE THREAD

**Issue by elroykanye** [istudybucket/istudybucket-backend#56]
**Describe the bug**
After a post is created, the created_date property in the json response for getting all posts displays a `null`

**To Reproduce**
1. Go to your favorite http client
2. Authenticate yourself and create a new request
3. Set the url for a new post from swagger-ui
4. Send a get request to `/api/post`

**Expected behavior**
The created date should show when each post was created.

**Screenshots**
![Screenshot_20220504_012608](https://user-images.githubusercontent.com/68631069/166608180-99dd5813-655b-4d98-a246-ff3f9fa08460.png)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser: Microsoft Edge
 - Version 99.0.1150.55 (Official build) (64-bit)

**Additional context**
N/A

**Comment by elroykanye** [comment]
This is as easy as changing the line in 
https://github.com/istudybucket/istudybucket-backend/blob/24fc73c0e0b044b5c9cc1e4708a1518bdc4e13a4/isb-library/src/main/java/com/elroykanye/istudybucket/data/entity/Post.java#L52

to

```java
private LocalDateTime createdDate = LocalDateTime.now();
```

**Comment by andrew21-mch** [comment]
alight, let me work on this first
